services:
  scraper:
    container_name: scraper
    build:
      context: .
      dockerfile: Dockerfile.scraper
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - scraper
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app

  your_service_name:
    image: your_image_name
    shm_size: 2g
